version: "3.8"

services:
  node-web-server:
    build:
      context: .\api
      dockerfile: .\Dockerfile
    container_name: node-web-server
    restart: always
    ports:
      - "3000:3000"

  react-app:
    build:
      context: .\client
      dockerfile: .\Dockerfile
    container_name: react-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - node-web-server
